//! Convert markdown to HTML, with fenced code blocks pre-highlighted
//! by `syntect` so the rendered page doesn't need a runtime
//! highlighter. The classed-HTML scheme lets every code span carry
//! its own `<span class>`es, and the matching CSS is generated once
//! from the bundled theme and written beside `index.html` as its own
//! linked stylesheet.

use pulldown_cmark::{CodeBlockKind, CowStr, Event, Options, Tag, TagEnd, html as cmark_html};
use std::sync::LazyLock;
use syntect::highlighting::ThemeSet;
use syntect::html::{ClassStyle, ClassedHTMLGenerator, css_for_theme_with_class_style};
use syntect::parsing::SyntaxSet;
use syntect::util::LinesWithEndings;

pub(crate) fn markdown_to_html(markdown: &str) -> String {
    let options =
        Options::ENABLE_TABLES | Options::ENABLE_STRIKETHROUGH | Options::ENABLE_FOOTNOTES;
    let parser = pulldown_cmark::Parser::new_ext(markdown, options);
    let events = highlight_code_blocks(parser);
    let mut buffer = String::new();
    cmark_html::push_html(&mut buffer, events.into_iter());
    buffer
}

/// Walk pulldown-cmark events, replacing fenced code blocks with
/// pre-highlighted HTML produced by `syntect`. The first comma-
/// separated token of the fence's info string is the language tag
/// (so `rust,ignore` is treated as Rust). Untagged fences pass
/// through to pulldown-cmark's default rendering; unknown tags are
/// highlighted as plain text.
fn highlight_code_blocks<'a>(parser: impl Iterator<Item = Event<'a>>) -> Vec<Event<'a>> {
    let mut out = Vec::new();
    let mut current_lang: Option<String> = None;
    let mut code_buffer = String::new();
    for event in parser {
        match event {
            Event::Start(Tag::CodeBlock(CodeBlockKind::Fenced(info))) => {
                let lang = info
                    .split(',')
                    .next()
                    .map(str::trim)
                    .filter(|part| !part.is_empty())
                    .map(str::to_owned);
                if let Some(lang) = lang {
                    current_lang = Some(lang);
                    code_buffer.clear();
                } else {
                    // Untagged fenced blocks have no language to highlight;
                    // let pulldown-cmark emit them as plain `<pre><code>`.
                    out.push(Event::Start(Tag::CodeBlock(CodeBlockKind::Fenced(info))));
                }
            }
            Event::End(TagEnd::CodeBlock) if current_lang.is_some() => {
                let lang = current_lang.take().expect("guarded above");
                let html = highlight_to_html(&code_buffer, &lang);
                out.push(Event::Html(CowStr::Boxed(html.into_boxed_str())));
            }
            Event::Text(text) if current_lang.is_some() => {
                code_buffer.push_str(&text);
            }
            other => out.push(other),
        }
    }
    out
}

fn highlight_to_html(code: &str, lang: &str) -> String {
    let syntax_set: &SyntaxSet = &SYNTAX_SET;
    let extension = match lang {
        "rust" => "rs",
        other => other,
    };
    let syntax = syntax_set
        .find_syntax_by_extension(extension)
        .or_else(|| syntax_set.find_syntax_by_name(lang))
        .or_else(|| syntax_set.find_syntax_by_token(lang))
        .unwrap_or_else(|| syntax_set.find_syntax_plain_text());
    let mut generator =
        ClassedHTMLGenerator::new_with_class_style(syntax, syntax_set, ClassStyle::Spaced);
    for line in LinesWithEndings::from(code) {
        // The classed generator only fails on malformed regex
        // matches, which can't happen against the bundled syntaxes.
        generator
            .parse_html_for_line_which_includes_newline(line)
            .expect("classed highlighting of bundled syntax should not fail");
    }
    let body = generator.finalize();
    let class_attr = lang_class_attr(lang);
    format!("<pre><code{class_attr}>{body}</code></pre>\n")
}

/// Render the `language-...` class attribute for a code block, but
/// only when the fence's language tag is made of characters that
/// are unambiguously safe to drop into an HTML attribute. Anything
/// outside the safe-character set yields an empty attribute — the page
/// still renders correctly because the inline `<span class>`es
/// generated by `syntect` carry the actual highlighting, and the
/// `language-...` class is purely decorative here.
fn lang_class_attr(lang: &str) -> String {
    let safe = !lang.is_empty()
        && lang.chars().all(|char| {
            char.is_ascii_alphanumeric() || matches!(char, '_' | '-' | '+' | '#' | '.')
        });
    if safe {
        format!(r#" class="language-{lang}""#)
    } else {
        String::new()
    }
}

// `two_face::syntax::extra_newlines` returns a `SyntaxSet` that
// supersets syntect's bundled defaults with extra languages —
// notably TOML, which several rules use in `dylint.toml`
// configuration snippets. Without it, fenced ```toml blocks fall
// through to syntect's plain-text fallback while ```rust blocks
// highlight normally.
static SYNTAX_SET: LazyLock<SyntaxSet> = LazyLock::new(two_face::syntax::extra_newlines);

/// The light and dark classed-highlight stylesheets.
///
/// Both are generated from one [`ThemeSet::load_defaults`] call (see
/// [`HIGHLIGHT_CSS`]). The `Theme` values themselves aren't kept — once
/// their CSS is generated, nothing else needs them — so this holds only
/// the two finished sheets.
pub(crate) struct HighlightCss {
    /// Light-mode sheet, written to `highlight-light.css`.
    pub(crate) light: String,
    /// Dark-mode sheet, written to `highlight-dark.css`.
    pub(crate) dark: String,
}

/// Light + dark highlight CSS, generated together.
///
/// [`ThemeSet::load_defaults`] parses the *entire* bundled theme set, so
/// it is called exactly once here and both themes are taken from that
/// single load — calling it per theme would parse the whole set twice.
pub(crate) static HIGHLIGHT_CSS: LazyLock<HighlightCss> = LazyLock::new(|| {
    let themes = ThemeSet::load_defaults().themes;
    let light = themes
        .get("InspiredGitHub")
        .expect("InspiredGitHub theme is bundled with syntect");
    let dark = themes
        .get("base16-eighties.dark")
        .expect("base16-eighties.dark theme is bundled with syntect");

    let light_css = css_for_theme_with_class_style(light, ClassStyle::Spaced)
        .expect("generating CSS for a bundled theme should not fail");
    let dark_raw = css_for_theme_with_class_style(dark, ClassStyle::Spaced)
        .expect("generating CSS for a bundled theme should not fail");
    // Both themes share the same span classes, so scope the dark sheet
    // under the system-preference tier (sans an explicit Light override)
    // and the explicit-Dark tier.
    let media = scope_highlight_css(&dark_raw, r#"html:not([color-scheme-override="light"])"#);
    let overridden = scope_highlight_css(&dark_raw, r#"html[color-scheme-override="dark"]"#);

    HighlightCss {
        light: light_css,
        dark: format!("@media (prefers-color-scheme: dark) {{\n{media}}}\n{overridden}"),
    }
});

/// Prefix every rule selector in a syntect-generated sheet with `scope`
/// so the rules apply only inside that ancestor. syntect emits one
/// selector line per rule — `<selectors> {`, where `<selectors>` may be
/// comma-separated compound selectors — with the declarations on the
/// following lines; the selector line is the only one that ends with
/// `{`. Comment lines (`/* ... */`), declaration lines, and the closing
/// `}` pass through untouched. Each comma-separated part is prefixed
/// individually, since a leading `scope ` only binds to the first
/// selector of a list otherwise.
fn scope_highlight_css(css: &str, scope: &str) -> String {
    let mut out = String::new();
    for line in css.lines() {
        if let Some(selectors) = line.trim_end().strip_suffix('{') {
            let scoped = selectors
                .split(',')
                .map(|selector| format!("{scope} {}", selector.trim()))
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&scoped);
            out.push_str(" {\n");
        } else {
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}

/// Render a short, single-line snippet of markdown without the
/// outer `<p>...</p>` wrapper that block-level rendering inserts. Used
/// for table cells and inline headings where backticks should still
/// turn into `<code>`.
pub(crate) fn markdown_inline_to_html(markdown: &str) -> String {
    let parser = pulldown_cmark::Parser::new(markdown).filter(|event| {
        !matches!(
            event,
            Event::Start(Tag::Paragraph) | Event::End(TagEnd::Paragraph),
        )
    });
    let mut buffer = String::new();
    cmark_html::push_html(&mut buffer, parser);
    buffer.trim_end().to_owned()
}

#[cfg(test)]
mod tests {
    use super::scope_highlight_css;

    #[test]
    fn scopes_each_selector_in_a_comma_list() {
        // syntect emits comma-separated compound selectors on the rule's
        // opening line; every part must be prefixed individually, or a
        // bare `scope ` would bind only to the first selector. Comment
        // lines, declarations, and the closing brace pass through.
        let input = "/* c */\n.a, .b .c {\n color: #fff;\n}\n";
        let scoped = scope_highlight_css(input, ":root[x]");
        assert_eq!(
            scoped,
            "/* c */\n:root[x] .a, :root[x] .b .c {\n color: #fff;\n}\n",
        );
    }
}
