name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Cache
        uses: actions/cache@v5
        timeout-minutes: 1
        continue-on-error: true
        with:
          path: |
            ~/.cargo
            target
          key: ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
            ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-

      - name: Install Rust
        shell: bash
        run: |
          installer=$(mktemp -d)/install-rustup
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > $installer
          bash $installer --default-toolchain none -y
          source "$HOME/.cargo/env"
          # Triggers rustup to install the toolchain and components from the
          # rust-toolchain override file (TOML format is required for `components`).
          rustup show active-toolchain || rustup show

      - name: Install Rust tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-dylint, dylint-link, just

      - name: Build
        shell: bash
        run: just build

      - name: Doc
        shell: bash
        run: just doc

      - name: Lint
        shell: bash
        run: just lint

      - name: Test
        shell: bash
        run: just test
