//! Render the extracted rule model as one markdown file per rule
//! plus a `README.md` index. The output is plain CommonMark with
//! GitHub-flavoured tables in the index; it deliberately doesn't
//! reuse the HTML renderer's `<details>` panels or the syntect
//! highlighter, since both rely on the page being rendered through
//! a browser. The trade-off is intentional: this markdown copy
//! exists so that a reader of the git repository can read the docs
//! without leaving their editor, and so that PRs that touch a rule
//! get an in-tree doc diff for review.
//!
//! Every rendered string ends with exactly one trailing newline so
//! the `check-md` byte-comparison stays stable across editors that
//! strip or add a final newline. Inline doc-comment prose is taken
//! verbatim — the extractor has already normalised the leading
//! convention space — and is wrapped in blank lines on either side
//! so it never glues itself to the headings around it.

use std::fmt::Write as _;

use crate::model::{
    ConfigDoc, ConfigField, EnumVariant, NAMESPACE, Rule, StructField, TypeDoc, TypeKind,
};

/// Per-rule markdown filename. Mirrors the source layout
/// (`src/rules/<name>.rs`) so a reader can find one from the other
/// by changing the extension.
pub(crate) fn rule_file_name(rule: &Rule) -> String {
    format!("{}.md", unnamespaced(&rule.namespaced))
}

/// Filename of the per-directory index. `README.md` so GitHub
/// renders it automatically when a user browses the `rules/`
/// directory in the web UI.
pub(crate) const INDEX_FILE_NAME: &str = "README.md";

/// Render one rule as a standalone markdown document.
pub(crate) fn render_rule_md(rule: &Rule) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# `{}`", rule.namespaced);
    out.push('\n');
    let _ = writeln!(
        out,
        "**Default level:** `{}`  ",
        rule.level.to_string().to_ascii_lowercase()
    );
    // The per-rule markdown lives one level down from the repo
    // root (typically `rules/<name>.md`), so the link to the rule
    // source has to climb back up before descending into `src/`.
    let source_path = source_path_str(rule);
    let _ = writeln!(out, "**Source:** [`{source_path}`](../{source_path})");
    out.push('\n');
    let _ = writeln!(out, "> {}", rule.short_desc);
    out.push('\n');
    if !rule.doc_markdown.is_empty() {
        out.push_str(&rule.doc_markdown);
        if !rule.doc_markdown.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }
    if let Some(config) = &rule.config {
        render_config_section(config, &mut out);
    } else {
        // Rules without a `Config`/`CONFIG_KEY` pair (in practice,
        // only `unknown_perfectionist_lints` today) get the same
        // "Configuration: none." stub the HTML renderer emits, for
        // the same reason: silence about configurability is
        // ambiguous; an explicit "none" is not.
        let _ = writeln!(out, "## Configuration");
        out.push('\n');
        let _ = writeln!(out, "None.");
        out.push('\n');
    }
    trim_trailing_blank_lines(&mut out);
    out
}

/// Render the `README.md` index that lists every rule. Mirrors the
/// HTML index table column-for-column: lint name (linked to the
/// per-rule file), default level, short description.
pub(crate) fn render_index_md(rules: &[Rule]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# perfectionist lints");
    out.push('\n');
    let _ = writeln!(
        out,
        "Auto-generated catalogue of implemented lints. Each row links to a per-rule \
         markdown file rendered from the same source as the [HTML \
         catalogue](https://ksxgithub.github.io/perfectionist/). Edit the rule source \
         in `src/rules/`, not these files; the in-tree copy is regenerated by \
         `cargo run --package _gen_docs --bin gen-docs -- write-md rules/`.",
    );
    out.push('\n');
    let _ = writeln!(
        out,
        "Lint-control attributes use the `{NAMESPACE}` namespace."
    );
    out.push('\n');
    let _ = writeln!(out, "| Lint | Default | Description |");
    let _ = writeln!(out, "| ---- | ------- | ----------- |");
    for rule in rules {
        let name = unnamespaced(&rule.namespaced);
        let _ = writeln!(
            out,
            "| [`{name}`](./{name}.md) | `{level}` | {desc} |",
            level = rule.level.to_string().to_ascii_lowercase(),
            desc = escape_pipes(&rule.short_desc),
        );
    }
    trim_trailing_blank_lines(&mut out);
    out
}

fn render_config_section(config: &ConfigDoc, out: &mut String) {
    let _ = writeln!(out, "## Configuration");
    out.push('\n');
    if config.fields.is_empty() {
        // The HTML renderer's matching branch suppresses the
        // struct-level doc comment for an empty `Config`; mirror
        // that here so the two output modes agree on what's
        // user-facing.
        let _ = writeln!(out, "None.");
        out.push('\n');
        return;
    }
    let _ = writeln!(
        out,
        "Configure via `dylint.toml` under `[\"{}\"]`. Every field is optional; the \
         per-field prose below states the default.",
        config.key,
    );
    out.push('\n');
    for field in &config.fields {
        render_field(field, out);
    }
    if !config.custom_types.is_empty() {
        let _ = writeln!(out, "### Types");
        out.push('\n');
        for ty in &config.custom_types {
            render_type(ty, out);
        }
    }
}

fn render_field(field: &ConfigField, out: &mut String) {
    let _ = writeln!(
        out,
        "### `{name}` — `{ty}` (optional)",
        name = field.name,
        ty = field.type_label,
    );
    out.push('\n');
    append_doc(&field.doc_markdown, out);
}

fn render_type(ty: &TypeDoc, out: &mut String) {
    let kind_label = match ty.kind {
        TypeKind::Enum { .. } => "enum",
        TypeKind::Struct { .. } => "struct",
    };
    let _ = writeln!(out, "#### `{name}` ({kind_label})", name = ty.name);
    out.push('\n');
    if !ty.doc_markdown.is_empty() {
        out.push_str(&ty.doc_markdown);
        if !ty.doc_markdown.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }
    match &ty.kind {
        TypeKind::Enum { variants } => {
            for variant in variants {
                render_variant(variant, out);
            }
        }
        TypeKind::Struct { fields } => {
            for field in fields {
                render_struct_field(field, out);
            }
        }
    }
}

fn render_variant(variant: &EnumVariant, out: &mut String) {
    if variant.rust_name == variant.serialized {
        let _ = writeln!(out, "##### `\"{}\"`", variant.serialized);
    } else {
        let _ = writeln!(
            out,
            "##### `\"{}\"` (Rust: `{}`)",
            variant.serialized, variant.rust_name,
        );
    }
    out.push('\n');
    append_doc(&variant.doc_markdown, out);
}

fn render_struct_field(field: &StructField, out: &mut String) {
    let _ = writeln!(
        out,
        "##### `{name}` — `{ty}`",
        name = field.name,
        ty = field.type_label,
    );
    out.push('\n');
    append_doc(&field.doc_markdown, out);
}

/// Append a doc-comment block, normalising trailing whitespace so
/// the surrounding heading-then-blank-line rhythm stays consistent.
/// An empty comment falls back to an italicised "Undocumented." —
/// the same placeholder the HTML renderer uses, for the same
/// reason: a silently empty section reads as a layout bug.
fn append_doc(doc: &str, out: &mut String) {
    if doc.is_empty() {
        let _ = writeln!(out, "*Undocumented.*");
    } else {
        out.push_str(doc);
        if !doc.ends_with('\n') {
            out.push('\n');
        }
    }
    out.push('\n');
}

fn unnamespaced(namespaced: &str) -> &str {
    namespaced.strip_prefix(NAMESPACE).unwrap_or(namespaced)
}

fn source_path_str(rule: &Rule) -> String {
    rule.relative_source
        .components()
        .map(|component| component.as_os_str().to_string_lossy().into_owned())
        .collect::<Vec<_>>()
        .join("/")
}

/// Escape the bare `|` characters that would otherwise terminate a
/// table cell. Backslash-escape is the GFM spec answer; everything
/// else (HTML entities, breaking the table) is uglier.
fn escape_pipes(text: &str) -> String {
    text.replace('|', "\\|")
}

/// Strip multiple trailing newlines down to exactly one. The
/// `writeln!` calls above leave a clean separator after the last
/// block; this function makes sure repeated blocks haven't piled up
/// blank lines at the document tail (some editors auto-trim them
/// and would otherwise dirty the check-md diff on every save).
fn trim_trailing_blank_lines(buffer: &mut String) {
    while buffer.ends_with("\n\n") {
        buffer.pop();
    }
    if !buffer.ends_with('\n') {
        buffer.push('\n');
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;
    use crate::model::{ConfigField, EnumVariant, Level, TypeDoc, TypeKind};

    fn fake_rule() -> Rule {
        Rule {
            namespaced: "perfectionist::demo_rule".to_owned(),
            level: Level::Warn,
            short_desc: "demo rule used in tests".to_owned(),
            doc_markdown: "### What it does\nDoes a demo.".to_owned(),
            relative_source: PathBuf::from("src/rules/demo_rule.rs"),
            config: None,
        }
    }

    #[test]
    fn rule_file_name_strips_namespace() {
        let rule = fake_rule();
        assert_eq!(rule_file_name(&rule), "demo_rule.md");
    }

    #[test]
    fn rule_md_includes_header_level_and_short_desc() {
        let md = render_rule_md(&fake_rule());
        assert!(md.starts_with("# `perfectionist::demo_rule`\n"));
        assert!(md.contains("**Default level:** `warn`"));
        assert!(md.contains("> demo rule used in tests"));
        assert!(md.ends_with('\n'));
        assert!(!md.ends_with("\n\n"));
    }

    #[test]
    fn rule_md_with_no_config_prints_none_section() {
        let md = render_rule_md(&fake_rule());
        assert!(md.contains("## Configuration"));
        assert!(md.contains("None."));
    }

    #[test]
    fn rule_md_with_config_lists_fields_and_types() {
        let mut rule = fake_rule();
        rule.config = Some(ConfigDoc {
            key: "perfectionist::demo_rule".to_owned(),
            fields: vec![ConfigField {
                name: "style".to_owned(),
                type_label: "Style".to_owned(),
                doc_markdown: "Pick a style.".to_owned(),
            }],
            custom_types: vec![TypeDoc {
                name: "Style".to_owned(),
                doc_markdown: "Style enum.".to_owned(),
                kind: TypeKind::Enum {
                    variants: vec![
                        EnumVariant {
                            rust_name: "Preserve".to_owned(),
                            serialized: "preserve".to_owned(),
                            doc_markdown: "Leave it alone.".to_owned(),
                        },
                        EnumVariant {
                            rust_name: "Same".to_owned(),
                            serialized: "Same".to_owned(),
                            doc_markdown: String::new(),
                        },
                    ],
                },
            }],
        });
        let md = render_rule_md(&rule);
        assert!(md.contains("### `style` — `Style` (optional)"));
        assert!(md.contains("Pick a style."));
        assert!(md.contains("#### `Style` (enum)"));
        // Renamed variant carries the Rust-side annotation.
        assert!(md.contains("##### `\"preserve\"`"));
        // Same-named variant doesn't.
        assert!(md.contains("##### `\"Same\"`"));
        assert!(!md.contains("(Rust: `Same`)"));
        // Empty doc fall-back.
        assert!(md.contains("*Undocumented.*"));
    }

    #[test]
    fn index_md_escapes_pipes() {
        let mut rule = fake_rule();
        rule.short_desc = "uses | inside".to_owned();
        let index = render_index_md(std::slice::from_ref(&rule));
        assert!(index.contains("uses \\| inside"));
        assert!(index.contains("[`demo_rule`](./demo_rule.md)"));
    }
}
