//! Render the extracted rule model as one markdown file per rule
//! plus a `README.md` index. The output is plain CommonMark; it
//! deliberately doesn't reuse the HTML renderer's `<details>`
//! panels or the syntect highlighter, since both rely on the page
//! being rendered through a browser. The trade-off is intentional:
//! this markdown copy exists so that a reader of the git
//! repository can read the docs without leaving their editor, and
//! so that PRs that touch a rule get an in-tree doc diff for
//! review.
//!
//! Every rendered string ends with exactly one trailing newline so
//! the `check-md` byte-comparison stays stable across editors that
//! strip or add a final newline. Inline doc-comment prose is taken
//! verbatim — the extractor has already normalised the leading
//! convention space — and is wrapped in blank lines on either side
//! so it never glues itself to the headings around it.

use std::fmt::Write as _;

use crate::model::{
    ConfigDoc, ConfigField, EnumVariant, NAMESPACE, Rule, StructField, TypeDoc, TypeKind,
};

/// Per-rule markdown filename. Mirrors the source layout
/// (`src/rules/<name>.rs`) so a reader can find one from the other
/// by changing the extension.
pub(crate) fn rule_file_name(rule: &Rule) -> String {
    format!("{}.md", unnamespaced(&rule.namespaced))
}

/// Filename of the per-directory index. `README.md` so GitHub
/// renders it automatically when a user browses the `rules/`
/// directory in the web UI.
pub(crate) const INDEX_FILE_NAME: &str = "README.md";

/// HTML comment prepended to every generated file. Serves the
/// reader of the markdown source (rather than the rendered page,
/// which strips it) by spelling out that the file is regenerated
/// from rule sources and naming the command that does it. Editing
/// the markdown directly is futile — the next `check-md` run flags
/// it as drift and `write-md` overwrites it — so the banner exists
/// to redirect any would-be editor to the right place before they
/// start typing.
const GENERATED_BANNER: &str = "<!-- Generated by `gen-docs write-md` from `src/rules/`. Do not edit by hand; run \
     `just gen-rules-md` after changing a rule source. -->";

/// Render one rule as a standalone markdown document.
///
/// `source_link_prefix` is the relative path from the rendered
/// markdown file back to the repo root, including a trailing `/`
/// when non-empty (e.g. `"../"` for the typical `rules/` layout,
/// `"../../"` for a `docs/lints/rules/` layout). Callers compute
/// it from the `rules_dir`-relative-to-`root` depth so the
/// rendered "Source:" link stays correct regardless of where the
/// catalogue is written.
pub(crate) fn render_rule_md(rule: &Rule, source_link_prefix: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{GENERATED_BANNER}");
    out.push('\n');
    let _ = writeln!(out, "# `{}`", rule.namespaced);
    out.push('\n');
    let _ = writeln!(out, "**Default state:** `{}`  ", rule.default_state.word());
    let source_path = source_path_str(rule);
    let _ = writeln!(
        out,
        "**Source:** [`{source_path}`]({source_link_prefix}{source_path})"
    );
    out.push('\n');
    let _ = writeln!(out, "> {}", rule.short_desc);
    out.push('\n');
    if !rule.doc_markdown.is_empty() {
        // The rule title above is `#` (h1), and the
        // `## Configuration` section below is `h2`. Source doc
        // comments by project convention use `### What it does` /
        // `### Why restrict this?` / `### Example` — i.e. h3,
        // which made sense in the rustdoc context where the rule
        // itself was h2 under the crate's h1. In this markdown
        // copy the rule *is* the h1, so source `h3` lands at the
        // same TOC depth as the h3 config field headings and the
        // reader can't tell sections apart from fields. Promote
        // the doc-comment's headings up one level so every
        // top-level prose section lands at h2, parallel to
        // `## Configuration`.
        let promoted = promote_headings(&rule.doc_markdown);
        out.push_str(&promoted);
        if !promoted.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }
    render_config_section(&rule.config, &mut out);
    trim_trailing_blank_lines(&mut out);
    out
}

/// Render the `README.md` index that lists every rule. A bullet
/// list rather than a table: the table form reads cleanly when
/// GitHub renders the page but its raw markdown source — which
/// every reviewer sees in PR diffs — is a wall of `|` pipes and
/// alignment dashes that's hard to scan.
pub(crate) fn render_index_md(rules: &[Rule]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{GENERATED_BANNER}");
    out.push('\n');
    let _ = writeln!(out, "# perfectionist lints");
    out.push('\n');
    let _ = writeln!(
        out,
        "Auto-generated catalogue of implemented lints. Each entry links to a per-rule \
         markdown file rendered from the same source as the [HTML \
         catalogue](https://ksxgithub.github.io/perfectionist/). Edit the rule source \
         in `src/rules/`, not these files; the in-tree copy is regenerated by \
         `just gen-rules-md`.",
    );
    out.push('\n');
    let _ = writeln!(
        out,
        "Lint-control attributes use the `{NAMESPACE}` namespace."
    );
    out.push('\n');
    for rule in rules {
        let name = unnamespaced(&rule.namespaced);
        // Split each entry across two lines: link + level on the
        // first, the short description as a continuation paragraph
        // after a blank line. The two-space indent on the
        // continuation is what CommonMark requires to keep the
        // paragraph attached to the list item; without it the
        // description would render as a sibling paragraph
        // following the list. The blank-line break makes the
        // entries scan as cards in the rendered page and keeps
        // long descriptions from running off the right margin in
        // the raw markdown source.
        let _ = writeln!(
            out,
            "- [`{name}`](./{name}.md) (default: `{state}`).",
            state = rule.default_state.word(),
        );
        let _ = writeln!(out);
        let _ = writeln!(out, "  {desc}", desc = rule.short_desc);
    }
    trim_trailing_blank_lines(&mut out);
    out
}

fn render_config_section(config: &ConfigDoc, out: &mut String) {
    let _ = writeln!(out, "## Configuration");
    out.push('\n');
    if config.fields.is_empty() {
        // The HTML renderer's matching branch suppresses the
        // struct-level doc comment for an empty `Config`; mirror
        // that here so the two output modes agree on what's
        // user-facing.
        let _ = writeln!(out, "None.");
        out.push('\n');
        return;
    }
    // Only nuance the optionality note when a field is actually
    // mandatory; rules whose fields are all optional keep the simpler
    // wording (and unchanged output).
    let optionality_note = if config.fields.iter().any(|field| field.required) {
        "Each field is optional unless marked mandatory"
    } else {
        "Every field is optional"
    };
    let _ = writeln!(
        out,
        "Configure via `dylint.toml` under `[\"{}\"]`. {optionality_note}; the per-field prose \
         below states the default.",
        config.key,
    );
    out.push('\n');
    for field in &config.fields {
        render_field(field, out);
    }
    if !config.custom_types.is_empty() {
        let _ = writeln!(out, "### Types");
        out.push('\n');
        for ty in &config.custom_types {
            render_type(ty, out);
        }
    }
}

fn render_field(field: &ConfigField, out: &mut String) {
    // `name: type` rather than `name — type`: the em dash isn't a
    // separator in English typography, it sets off parenthetical
    // prose. The HTML renderer uses `:` for the same reason.
    let _ = writeln!(
        out,
        "### `{name}`: `{ty}` ({optionality})",
        name = field.name,
        ty = field.type_label,
        optionality = if field.required {
            "mandatory"
        } else {
            "optional"
        },
    );
    out.push('\n');
    append_doc(&field.doc_markdown, out);
}

fn render_type(ty: &TypeDoc, out: &mut String) {
    let kind_label = match ty.kind {
        TypeKind::Enum { .. } => "enum",
        TypeKind::Struct { .. } => "struct",
    };
    let _ = writeln!(out, "#### `{name}` ({kind_label})", name = ty.name);
    out.push('\n');
    if !ty.doc_markdown.is_empty() {
        out.push_str(&ty.doc_markdown);
        if !ty.doc_markdown.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }
    match &ty.kind {
        TypeKind::Enum { variants } => {
            for variant in variants {
                render_variant(variant, out);
            }
        }
        TypeKind::Struct { fields } => {
            for field in fields {
                render_struct_field(field, out);
            }
        }
    }
}

fn render_variant(variant: &EnumVariant, out: &mut String) {
    if variant.rust_name == variant.serialized {
        let _ = writeln!(out, "##### `\"{}\"`", variant.serialized);
    } else {
        let _ = writeln!(
            out,
            "##### `\"{}\"` (Rust: `{}`)",
            variant.serialized, variant.rust_name,
        );
    }
    out.push('\n');
    append_doc(&variant.doc_markdown, out);
}

fn render_struct_field(field: &StructField, out: &mut String) {
    let _ = writeln!(
        out,
        "##### `{name}`: `{ty}`",
        name = field.name,
        ty = field.type_label,
    );
    out.push('\n');
    append_doc(&field.doc_markdown, out);
}

/// Append a doc-comment block, normalising trailing whitespace so
/// the surrounding heading-then-blank-line rhythm stays consistent.
/// An empty comment falls back to an italicised "Undocumented." —
/// the same placeholder the HTML renderer uses, for the same
/// reason: a silently empty section reads as a layout bug.
fn append_doc(doc: &str, out: &mut String) {
    if doc.is_empty() {
        let _ = writeln!(out, "*Undocumented.*");
    } else {
        out.push_str(doc);
        if !doc.ends_with('\n') {
            out.push('\n');
        }
    }
    out.push('\n');
}

fn unnamespaced(namespaced: &str) -> &str {
    namespaced.strip_prefix(NAMESPACE).unwrap_or(namespaced)
}

/// Render a path with `/` separators even on Windows. The path
/// appears inside a markdown link, where `/` is the only separator
/// browsers and Git's blob viewer interpret correctly. Joining by
/// `Path::display()` would emit `\` on Windows and break the link.
fn source_path_str(rule: &Rule) -> String {
    rule.relative_source
        .components()
        .map(|component| component.as_os_str().to_string_lossy().into_owned())
        .collect::<Vec<_>>()
        .join("/")
}

/// Promote every ATX heading in a markdown block up by one level
/// (`### foo` → `## foo`), leaving `#` (h1) lines alone. Used to
/// align source-level doc-comment headings (`### What it does`)
/// with the rule's outer document layout, where `## Configuration`
/// is h2 and config-field headings are h3.
///
/// The function deliberately ignores headings inside fenced code
/// blocks — a literal `### foo` line inside a triple-backtick
/// fence is code text, not a heading, and rewriting it would
/// silently corrupt rendered examples. Indented-code blocks (4+
/// leading spaces) are similarly skipped. ATX headings can have up
/// to 3 leading spaces per CommonMark; beyond that the line is no
/// longer a heading.
fn promote_headings(markdown: &str) -> String {
    let mut out = String::with_capacity(markdown.len());
    // Track the open fence's marker character and length per
    // CommonMark §4.5: a fenced code block opened with N
    // backticks closes only on a line of M ≥ N backticks (and
    // nothing else); the same rule with `~`. The two fence
    // characters are independent — a `~~~` inside a triple-
    // backtick block is body content, not a close marker.
    // Storing only a `bool` would incorrectly toggle on either,
    // and a future rule whose example used both kinds of fence
    // would silently corrupt rendered output.
    let mut open_fence: Option<(u8, usize)> = None;
    for line in markdown.split_inclusive('\n') {
        // Per CommonMark §4.5, a fence-marker line (open or
        // close) carries at most 3 leading spaces. A line with 4+
        // leading spaces is an indented-code-block line, not a
        // fence — even if its first non-whitespace bytes are
        // backticks. Compute `leading_spaces` first and only
        // consider the line as a fence marker when it's within
        // the allowance.
        let leading_spaces = line.bytes().take_while(|&b| b == b' ').count();
        if leading_spaces < 4 {
            let after_leading = &line[leading_spaces..];
            let fence_marker = if after_leading.starts_with("```") {
                Some(b'`')
            } else if after_leading.starts_with("~~~") {
                Some(b'~')
            } else {
                None
            };
            if let Some(marker) = fence_marker {
                let length = after_leading.bytes().take_while(|&b| b == marker).count();
                // After the marker run, the rest of the line
                // decides whether this is a valid close fence.
                // Per CommonMark §4.5, a close fence cannot carry
                // an info string — only optional trailing
                // whitespace. An open fence may carry one
                // (`` ```rust ``). Treat any line whose
                // post-marker tail is non-whitespace as body text
                // when an open fence already exists, so a literal
                // `` ```rust `` line nested inside a wider outer
                // fence isn't mistaken for a close.
                let after_markers = &after_leading[length..];
                let tail_is_blank = after_markers.trim().is_empty();
                match open_fence {
                    None => {
                        open_fence = Some((marker, length));
                    }
                    Some((open_marker, open_length))
                        if open_marker == marker && length >= open_length && tail_is_blank =>
                    {
                        open_fence = None;
                    }
                    Some(_) => {
                        // Mismatched marker, shorter run, or
                        // non-blank tail: body content of the
                        // open fence, not a close marker. Stay
                        // inside the fence.
                    }
                }
                out.push_str(line);
                continue;
            }
        }
        if open_fence.is_some() {
            out.push_str(line);
            continue;
        }
        if leading_spaces >= 4 {
            // Indented code block (outside any fenced block).
            out.push_str(line);
            continue;
        }
        let rest = &line[leading_spaces..];
        let hash_count = rest.bytes().take_while(|&b| b == b'#').count();
        let after_hashes = &rest[hash_count..];
        // ATX heading requires a space (or end-of-line) after the
        // hash run; (2..=6) lets us promote h2-h6 but skip h1
        // (which would otherwise become an empty `# `).
        if (2..=6).contains(&hash_count)
            && (after_hashes.starts_with(' ') || after_hashes.starts_with('\n'))
        {
            for _ in 0..leading_spaces {
                out.push(' ');
            }
            for _ in 0..(hash_count - 1) {
                out.push('#');
            }
            out.push_str(after_hashes);
        } else {
            out.push_str(line);
        }
    }
    out
}

/// Strip multiple trailing newlines down to exactly one. The
/// `writeln!` calls above leave a clean separator after the last
/// block; this function makes sure repeated blocks haven't piled up
/// blank lines at the document tail (some editors auto-trim them
/// and would otherwise dirty the check-md diff on every save).
fn trim_trailing_blank_lines(buffer: &mut String) {
    while buffer.ends_with("\n\n") {
        buffer.pop();
    }
    if !buffer.ends_with('\n') {
        buffer.push('\n');
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;
    use crate::model::{ConfigField, DefaultState, EnumVariant, TypeDoc, TypeKind};

    fn fake_rule() -> Rule {
        Rule {
            namespaced: "perfectionist::demo_rule".to_owned(),
            default_state: DefaultState::Active,
            short_desc: "demo rule used in tests".to_owned(),
            doc_markdown: "### What it does\nDoes a demo.".to_owned(),
            relative_source: PathBuf::from("src/rules/demo_rule.rs"),
            config: ConfigDoc {
                key: "perfectionist::demo_rule".to_owned(),
                fields: Vec::new(),
                custom_types: Vec::new(),
            },
        }
    }

    #[test]
    fn rule_file_name_strips_namespace() {
        let rule = fake_rule();
        assert_eq!(rule_file_name(&rule), "demo_rule.md");
    }

    #[test]
    fn rule_md_includes_header_state_and_short_desc() {
        let md = render_rule_md(&fake_rule(), "../");
        assert!(md.contains("# `perfectionist::demo_rule`\n"));
        assert!(md.contains("**Default state:** `active`"));
        assert!(md.contains("> demo rule used in tests"));
        assert!(md.ends_with('\n'));
        assert!(!md.ends_with("\n\n"));
    }

    #[test]
    fn rule_md_renders_inactive_state_for_opt_in_rules() {
        let mut rule = fake_rule();
        rule.default_state = DefaultState::Inactive;
        let md = render_rule_md(&rule, "../");
        assert!(md.contains("**Default state:** `inactive`"));
    }

    #[test]
    fn rule_md_with_no_config_prints_none_section() {
        let md = render_rule_md(&fake_rule(), "../");
        assert!(md.contains("## Configuration"));
        assert!(md.contains("None."));
    }

    #[test]
    fn rule_md_with_config_lists_fields_and_types() {
        let mut rule = fake_rule();
        rule.config = ConfigDoc {
            key: "perfectionist::demo_rule".to_owned(),
            fields: vec![
                // `doc_markdown` is post-extraction: the `**Mandatory.**`
                // sentinel has already been stripped (see
                // `extract::config::split_mandatory_sentinel`).
                ConfigField {
                    name: "style".to_owned(),
                    type_label: "Style".to_owned(),
                    doc_markdown: "Pick a style.".to_owned(),
                    required: true,
                },
                ConfigField {
                    name: "extras".to_owned(),
                    type_label: "[string]".to_owned(),
                    doc_markdown: "Extra entries.".to_owned(),
                    required: false,
                },
            ],
            custom_types: vec![TypeDoc {
                name: "Style".to_owned(),
                doc_markdown: "Style enum.".to_owned(),
                kind: TypeKind::Enum {
                    variants: vec![
                        EnumVariant {
                            rust_name: "Preserve".to_owned(),
                            serialized: "preserve".to_owned(),
                            doc_markdown: "Leave it alone.".to_owned(),
                        },
                        EnumVariant {
                            rust_name: "Same".to_owned(),
                            serialized: "Same".to_owned(),
                            doc_markdown: String::new(),
                        },
                    ],
                },
            }],
        };
        let md = render_rule_md(&rule, "../");
        // A `required` field renders the `mandatory` marker, not `optional`.
        assert!(md.contains("### `style`: `Style` (mandatory)"));
        assert!(!md.contains("### `style`: `Style` (optional)"));
        // An ordinary field still renders `optional`.
        assert!(md.contains("### `extras`: `[string]` (optional)"));
        assert!(md.contains("Pick a style."));
        assert!(md.contains("#### `Style` (enum)"));
        // Renamed variant carries the Rust-side annotation.
        assert!(md.contains("##### `\"preserve\"`"));
        // Same-named variant doesn't.
        assert!(md.contains("##### `\"Same\"`"));
        assert!(!md.contains("(Rust: `Same`)"));
        // Empty doc fall-back.
        assert!(md.contains("*Undocumented.*"));
    }

    #[test]
    fn index_md_renders_bullet_list() {
        let mut rule = fake_rule();
        rule.short_desc = "uses | inside".to_owned();
        let index = render_index_md(std::slice::from_ref(&rule));
        // Each entry spans two lines: the link/state line, then a
        // blank line, then the indented short-description
        // continuation paragraph.
        assert!(index.contains("- [`demo_rule`](./demo_rule.md) (default: `active`).\n"));
        assert!(index.contains("\n  uses | inside\n"));
        // The bullet-list form needs no `|` escaping (unlike a
        // table) — the pipe in the description appears raw.
        assert!(!index.contains("\\|"));
    }

    #[test]
    fn rule_md_starts_with_generated_banner() {
        let md = render_rule_md(&fake_rule(), "../");
        assert!(md.starts_with("<!-- Generated by `gen-docs write-md`"));
    }

    #[test]
    fn index_md_starts_with_generated_banner() {
        let index = render_index_md(&[fake_rule()]);
        assert!(index.starts_with("<!-- Generated by `gen-docs write-md`"));
    }

    #[test]
    fn doc_markdown_headings_are_promoted_one_level() {
        // The rule title is h1 and `## Configuration` is h2. A
        // source-level `### What it does` should render as `## What
        // it does` so prose sections sit parallel to Configuration
        // instead of at the same depth as h3 config fields.
        let mut rule = fake_rule();
        rule.doc_markdown =
            "### What it does\nDoes a demo.\n\n### Example\n```text\n### not a heading\n```"
                .to_owned();
        let md = render_rule_md(&rule, "../");
        assert!(md.contains("\n## What it does\n"), "got:\n{md}");
        assert!(md.contains("\n## Example\n"), "got:\n{md}");
        // The `###` line inside the fenced code block must stay
        // untouched, since it's example text, not a heading.
        assert!(md.contains("### not a heading"), "got:\n{md}");
        // And the original h3 must not survive at top level.
        assert!(!md.contains("\n### What it does\n"), "got:\n{md}");
    }

    #[test]
    fn promote_headings_leaves_h1_alone() {
        // Demoting h1 would produce `# ` with no content. Source
        // markdown shouldn't have h1 anyway (the rule title takes
        // that slot), but if it appears, leave it intact rather
        // than mangling it.
        let out = promote_headings("# Title\nBody.\n");
        assert_eq!(out, "# Title\nBody.\n");
    }

    #[test]
    fn promote_headings_caps_at_h6() {
        // h6 promoted would be h5; nothing past h6 to worry about.
        // A line of seven `#` is not a heading per CommonMark.
        let out = promote_headings("####### not a heading\n");
        assert_eq!(out, "####### not a heading\n");
    }

    #[test]
    fn promote_headings_distinguishes_fence_markers() {
        // A triple-backtick fence stays open through a `~~~` line
        // in its body — `~~~` is the wrong marker, so it's not a
        // close — and any `## inside` between them must not be
        // treated as a heading. Per CommonMark §4.5, fence char
        // and length both matter for the close.
        let input = "```rust\n## inside backtick fence\n~~~\nstill inside\n```\n## outside\n";
        let out = promote_headings(input);
        // The body lines pass through verbatim.
        assert!(
            out.contains("## inside backtick fence\n"),
            "body should be untouched: {out}"
        );
        assert!(out.contains("~~~\n"), "tilde line should pass: {out}");
        // The line after the close-fence is outside; promote it.
        assert!(out.contains("# outside\n"), "outside promoted: {out}");
        assert!(
            !out.contains("\n## outside\n"),
            "outside should be promoted, not left at h2: {out}"
        );
    }

    #[test]
    fn promote_headings_treats_indented_fence_marker_as_indented_code() {
        // Per CommonMark §4.5, a fence opener may be indented at
        // most 3 spaces; with 4+ spaces it's an indented code
        // block, not a fence. The previous implementation
        // trimmed *all* leading whitespace before checking for
        // backticks, so a `    ```` line opened a phantom fence
        // and any subsequent heading line was suppressed.
        let input = "    ```\n    ## inside indented code\n    ```\n## outside\n";
        let out = promote_headings(input);
        // The indented `` ``` `` lines pass through verbatim.
        assert!(
            out.contains("    ```\n"),
            "indented backticks should not open a fence: {out}"
        );
        // The 4-space-indented heading is inside an indented
        // code block, so it stays untouched too.
        assert!(
            out.contains("    ## inside indented code\n"),
            "indented heading should not be promoted: {out}"
        );
        // The unindented heading outside is promoted normally.
        assert!(
            out.contains("\n# outside\n"),
            "trailing heading should be promoted: {out}"
        );
    }

    #[test]
    fn promote_headings_rejects_info_string_as_close_fence() {
        // Per CommonMark §4.5, the close fence cannot carry an
        // info string. A nested `` ```rust `` line inside a wider
        // outer fence is body, not a close.
        let input = "````\n## inside\n```rust\n## still inside\n````\n## outside\n";
        let out = promote_headings(input);
        assert!(
            out.contains("## inside\n"),
            "body heading should not be promoted: {out}"
        );
        assert!(
            out.contains("## still inside\n"),
            "heading after the bogus close should still be body: {out}"
        );
        // The real close (4 backticks alone) ends the fence.
        assert!(
            out.contains("# outside\n"),
            "outside should be promoted: {out}"
        );
    }

    #[test]
    fn promote_headings_requires_matching_close_length() {
        // Per CommonMark §4.5, a fence opened with 4 backticks
        // closes only on ≥ 4 backticks. A 3-backtick line inside
        // is body, not a close.
        let input = "````\n```\n## inside long fence\n````\n## outside\n";
        let out = promote_headings(input);
        assert!(
            out.contains("## inside long fence\n"),
            "inside long fence should pass: {out}"
        );
        assert!(out.contains("# outside\n"), "outside promoted: {out}");
    }
}
